#ifndef __gl_mangle_h_
#define __gl_mangle_h_

/* GLES 2.0 */
#define glActiveTexture axglActiveTexture
#define glAttachShader axglAttachShader
#define glBindAttribLocation axglBindAttribLocation
#define glBindBuffer axglBindBuffer
#define glBindFramebuffer axglBindFramebuffer
#define glBindRenderbuffer axglBindRenderbuffer
#define glBindTexture axglBindTexture 
#define glBlendColor axglBlendColor 
#define glBlendEquation axglBlendEquation 
#define glBlendEquationSeparate axglBlendEquationSeparate 
#define glBlendFunc axglBlendFunc 
#define glBlendFuncSeparate axglBlendFuncSeparate 
#define glBufferData axglBufferData 
#define glBufferSubData axglBufferSubData 
#define glCheckFramebufferStatus axglCheckFramebufferStatus 
#define glClear axglClear 
#define glClearColor axglClearColor 
#define glClearDepthf axglClearDepthf 
#define glClearStencil axglClearStencil 
#define glColorMask axglColorMask 
#define glCompileShader axglCompileShader 
#define glCompressedTexImage2D axglCompressedTexImage2D 
#define glCompressedTexSubImage2D axglCompressedTexSubImage2D 
#define glCopyTexImage2D axglCopyTexImage2D 
#define glCopyTexSubImage2D axglCopyTexSubImage2D 
#define glCreateProgram axglCreateProgram 
#define glCreateShader axglCreateShader 
#define glCullFace axglCullFace 
#define glDeleteBuffers axglDeleteBuffers 
#define glDeleteFramebuffers axglDeleteFramebuffers 
#define glDeleteProgram axglDeleteProgram 
#define glDeleteRenderbuffers axglDeleteRenderbuffers 
#define glDeleteShader axglDeleteShader 
#define glDeleteTextures axglDeleteTextures 
#define glDepthFunc axglDepthFunc 
#define glDepthMask axglDepthMask 
#define glDepthRangef axglDepthRangef 
#define glDetachShader axglDetachShader 
#define glDisable axglDisable 
#define glDisableVertexAttribArray axglDisableVertexAttribArray 
#define glDrawArrays axglDrawArrays 
#define glDrawElements axglDrawElements 
#define glEnable axglEnable 
#define glEnableVertexAttribArray axglEnableVertexAttribArray 
#define glFinish axglFinish 
#define glFlush axglFlush 
#define glFramebufferRenderbuffer axglFramebufferRenderbuffer 
#define glFramebufferTexture2D axglFramebufferTexture2D 
#define glFrontFace axglFrontFace 
#define glGenBuffers axglGenBuffers 
#define glGenerateMipmap axglGenerateMipmap 
#define glGenFramebuffers axglGenFramebuffers 
#define glGenRenderbuffers axglGenRenderbuffers 
#define glGenTextures axglGenTextures 
#define glGetActiveAttrib axglGetActiveAttrib 
#define glGetActiveUniform axglGetActiveUniform 
#define glGetAttachedShaders axglGetAttachedShaders 
#define glGetAttribLocation axglGetAttribLocation 
#define glGetBooleanv axglGetBooleanv 
#define glGetBufferParameteriv axglGetBufferParameteriv 
#define glGetError axglGetError 
#define glGetFloatv axglGetFloatv 
#define glGetFramebufferAttachmentParameteriv axglGetFramebufferAttachmentParameteriv 
#define glGetIntegerv axglGetIntegerv 
#define glGetProgramiv axglGetProgramiv 
#define glGetProgramInfoLog axglGetProgramInfoLog 
#define glGetRenderbufferParameteriv axglGetRenderbufferParameteriv 
#define glGetShaderiv axglGetShaderiv 
#define glGetShaderInfoLog axglGetShaderInfoLog 
#define glGetShaderPrecisionFormat axglGetShaderPrecisionFormat 
#define glGetShaderSource axglGetShaderSource 
#define glGetString axglGetString 
#define glGetTexParameterfv axglGetTexParameterfv 
#define glGetTexParameteriv axglGetTexParameteriv 
#define glGetUniformfv axglGetUniformfv 
#define glGetUniformiv axglGetUniformiv 
#define glGetUniformLocation axglGetUniformLocation 
#define glGetVertexAttribfv axglGetVertexAttribfv 
#define glGetVertexAttribiv axglGetVertexAttribiv 
#define glGetVertexAttribPointerv axglGetVertexAttribPointerv 
#define glHint axglHint 
#define glIsBuffer axglIsBuffer 
#define glIsEnabled axglIsEnabled 
#define glIsFramebuffer axglIsFramebuffer 
#define glIsProgram axglIsProgram 
#define glIsRenderbuffer axglIsRenderbuffer 
#define glIsShader axglIsShader 
#define glIsTexture axglIsTexture 
#define glLineWidth axglLineWidth 
#define glLinkProgram axglLinkProgram 
#define glPixelStorei axglPixelStorei 
#define glPolygonOffset axglPolygonOffset 
#define glReadPixels axglReadPixels 
#define glReleaseShaderCompiler axglReleaseShaderCompiler 
#define glRenderbufferStorage axglRenderbufferStorage 
#define glSampleCoverage axglSampleCoverage 
#define glScissor axglScissor 
#define glShaderBinary axglShaderBinary 
#define glShaderSource axglShaderSource 
#define glStencilFunc axglStencilFunc 
#define glStencilFuncSeparate axglStencilFuncSeparate 
#define glStencilMask axglStencilMask 
#define glStencilMaskSeparate axglStencilMaskSeparate 
#define glStencilOp axglStencilOp 
#define glStencilOpSeparate axglStencilOpSeparate 
#define glTexImage2D axglTexImage2D 
#define glTexParameterf axglTexParameterf 
#define glTexParameterfv axglTexParameterfv 
#define glTexParameteri axglTexParameteri 
#define glTexParameteriv axglTexParameteriv 
#define glTexSubImage2D axglTexSubImage2D 
#define glUniform1f axglUniform1f 
#define glUniform1fv axglUniform1fv 
#define glUniform1i axglUniform1i 
#define glUniform1iv axglUniform1iv 
#define glUniform2f axglUniform2f 
#define glUniform2fv axglUniform2fv 
#define glUniform2i axglUniform2i 
#define glUniform2iv axglUniform2iv 
#define glUniform3f axglUniform3f 
#define glUniform3fv axglUniform3fv 
#define glUniform3i axglUniform3i 
#define glUniform3iv axglUniform3iv 
#define glUniform4f axglUniform4f 
#define glUniform4fv axglUniform4fv 
#define glUniform4i axglUniform4i 
#define glUniform4iv axglUniform4iv 
#define glUniformMatrix2fv axglUniformMatrix2fv 
#define glUniformMatrix3fv axglUniformMatrix3fv 
#define glUniformMatrix4fv axglUniformMatrix4fv 
#define glUseProgram axglUseProgram 
#define glValidateProgram axglValidateProgram 
#define glVertexAttrib1f axglVertexAttrib1f 
#define glVertexAttrib1fv axglVertexAttrib1fv 
#define glVertexAttrib2f axglVertexAttrib2f 
#define glVertexAttrib2fv axglVertexAttrib2fv 
#define glVertexAttrib3f axglVertexAttrib3f 
#define glVertexAttrib3fv axglVertexAttrib3fv 
#define glVertexAttrib4f axglVertexAttrib4f 
#define glVertexAttrib4fv axglVertexAttrib4fv 
#define glVertexAttribPointer axglVertexAttribPointer 
#define glViewport axglViewport 

/* GLES 3.0 */
#define glReadBuffer axglReadBuffer 
#define glDrawRangeElements axglDrawRangeElements 
#define glTexImage3D axglTexImage3D 
#define glTexSubImage3D axglTexSubImage3D 
#define glCopyTexSubImage3D axglCopyTexSubImage3D 
#define glCompressedTexImage3D axglCompressedTexImage3D 
#define glCompressedTexSubImage3D axglCompressedTexSubImage3D 
#define glGenQueries axglGenQueries 
#define glDeleteQueries axglDeleteQueries 
#define glIsQuery axglIsQuery 
#define glBeginQuery axglBeginQuery 
#define glEndQuery axglEndQuery 
#define glGetQueryiv axglGetQueryiv 
#define glGetQueryObjectuiv axglGetQueryObjectuiv 
#define glUnmapBuffer axglUnmapBuffer 
#define glGetBufferPointerv axglGetBufferPointerv 
#define glDrawBuffers axglDrawBuffers 
#define glUniformMatrix2x3fv axglUniformMatrix2x3fv 
#define glUniformMatrix3x2fv axglUniformMatrix3x2fv 
#define glUniformMatrix2x4fv axglUniformMatrix2x4fv 
#define glUniformMatrix4x2fv axglUniformMatrix4x2fv 
#define glUniformMatrix3x4fv axglUniformMatrix3x4fv 
#define glUniformMatrix4x3fv axglUniformMatrix4x3fv 
#define glBlitFramebuffer axglBlitFramebuffer 
#define glRenderbufferStorageMultisample axglRenderbufferStorageMultisample 
#define glFramebufferTextureLayer axglFramebufferTextureLayer 
#define glMapBufferRange axglMapBufferRange 
#define glFlushMappedBufferRange axglFlushMappedBufferRange 
#define glBindVertexArray axglBindVertexArray 
#define glDeleteVertexArrays axglDeleteVertexArrays 
#define glGenVertexArrays axglGenVertexArrays 
#define glIsVertexArray axglIsVertexArray 
#define glGetIntegeri_v axglGetIntegeri_v 
#define glBeginTransformFeedback axglBeginTransformFeedback 
#define glEndTransformFeedback axglEndTransformFeedback 
#define glBindBufferRange axglBindBufferRange 
#define glBindBufferBase axglBindBufferBase 
#define glTransformFeedbackVaryings axglTransformFeedbackVaryings 
#define glGetTransformFeedbackVarying axglGetTransformFeedbackVarying 
#define glVertexAttribIPointer axglVertexAttribIPointer 
#define glGetVertexAttribIiv axglGetVertexAttribIiv 
#define glGetVertexAttribIuiv axglGetVertexAttribIuiv 
#define glVertexAttribI4i axglVertexAttribI4i 
#define glVertexAttribI4ui axglVertexAttribI4ui 
#define glVertexAttribI4iv axglVertexAttribI4iv 
#define glVertexAttribI4uiv axglVertexAttribI4uiv 
#define glGetUniformuiv axglGetUniformuiv 
#define glGetFragDataLocation axglGetFragDataLocation 
#define glUniform1ui axglUniform1ui 
#define glUniform2ui axglUniform2ui 
#define glUniform3ui axglUniform3ui 
#define glUniform4ui axglUniform4ui 
#define glUniform1uiv axglUniform1uiv 
#define glUniform2uiv axglUniform2uiv 
#define glUniform3uiv axglUniform3uiv 
#define glUniform4uiv axglUniform4uiv 
#define glClearBufferiv axglClearBufferiv 
#define glClearBufferuiv axglClearBufferuiv 
#define glClearBufferfv axglClearBufferfv 
#define glClearBufferfi axglClearBufferfi 
#define glGetStringi axglGetStringi 
#define glCopyBufferSubData axglCopyBufferSubData 
#define glGetUniformIndices axglGetUniformIndices 
#define glGetActiveUniformsiv axglGetActiveUniformsiv 
#define glGetUniformBlockIndex axglGetUniformBlockIndex 
#define glGetActiveUniformBlockiv axglGetActiveUniformBlockiv 
#define glGetActiveUniformBlockName axglGetActiveUniformBlockName 
#define glUniformBlockBinding axglUniformBlockBinding 
#define glDrawArraysInstanced axglDrawArraysInstanced 
#define glDrawElementsInstanced axglDrawElementsInstanced 
#define glFenceSync axglFenceSync 
#define glIsSync axglIsSync 
#define glDeleteSync axglDeleteSync 
#define glClientWaitSync axglClientWaitSync 
#define glWaitSync axglWaitSync 
#define glGetInteger64v axglGetInteger64v 
#define glGetSynciv axglGetSynciv 
#define glGetInteger64i_v axglGetInteger64i_v 
#define glGetBufferParameteri64v axglGetBufferParameteri64v 
#define glGenSamplers axglGenSamplers 
#define glDeleteSamplers axglDeleteSamplers 
#define glIsSampler axglIsSampler 
#define glBindSampler axglBindSampler 
#define glSamplerParameteri axglSamplerParameteri 
#define glSamplerParameteriv axglSamplerParameteriv 
#define glSamplerParameterf axglSamplerParameterf 
#define glSamplerParameterfv axglSamplerParameterfv 
#define glGetSamplerParameteriv axglGetSamplerParameteriv 
#define glGetSamplerParameterfv axglGetSamplerParameterfv 
#define glVertexAttribDivisor axglVertexAttribDivisor 
#define glBindTransformFeedback axglBindTransformFeedback 
#define glDeleteTransformFeedbacks axglDeleteTransformFeedbacks 
#define glGenTransformFeedbacks axglGenTransformFeedbacks 
#define glIsTransformFeedback axglIsTransformFeedback 
#define glPauseTransformFeedback axglPauseTransformFeedback 
#define glResumeTransformFeedback axglResumeTransformFeedback 
#define glGetProgramBinary axglGetProgramBinary 
#define glProgramBinary axglProgramBinary 
#define glProgramParameteri axglProgramParameteri 
#define glInvalidateFramebuffer axglInvalidateFramebuffer 
#define glInvalidateSubFramebuffer axglInvalidateSubFramebuffer 
#define glTexStorage2D axglTexStorage2D 
#define glTexStorage3D axglTexStorage3D 
#define glGetInternalformativ axglGetInternalformativ 

/* extension */
#define glInvalidateCacheAXGL axglInvalidateCache

#endif /* __gl_mangle_h_ */
